version: '2'
services:
  db:
    container_name: postgres
    image: postgres:10
    ports:
      - "${DB_PORT}:${DB_PORT}"
  web:
    container_name: web
    build: .
    # Wait for DB, create schema, seed data and start app.
    command: bash -c "sleep 3; bundle exec rake db:migrate && bundle exec rake db:seed && bundle exec rake serve"
    volumes:
      - .:/web
    ports:
      - "${DEV_PORT}:${DEV_PORT}"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
